const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.CSV,
		C3.Plugins.Touch,
		C3.Plugins.HTMLElement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.HTMLElement.Cnds.OnCreated,
		C3.Plugins.HTMLElement.Acts.SetContent
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{dir: 0},
	{clicked: 0},
	{Tween: 0},
	{arrow: 0},
	{unitName: 0},
	{maxUnit: 0},
	{icons: 0},
	{Titles: 0},
	{TiledBackground: 0},
	{id: 0},
	{subjectTitle: 0},
	{unit: 0},
	{lessonNum: 0},
	{v_counter: 0},
	{Pin: 0},
	{lesson_text: 0},
	{Array: 0},
	{CSV: 0},
	{subject: 0},
	{unitNumber: 0},
	{MaxLessonsNum: 0},
	{lessonsTitles: 0},
	{v_lessons_title: 0},
	{Touch: 0},
	{numbers: 0},
	{HTMLElement: 0},
	{seen: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	icons: class extends self.ISpriteInstance {},
	Titles: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	subjectTitle: class extends self.ISpriteInstance {},
	v_counter: class extends self.ISpriteInstance {},
	lesson_text: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	CSV: class extends self.IInstance {},
	v_lessons_title: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	numbers: class extends self.ITextInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	seen: class extends self.ISpriteInstance {}
}